package com.fdk.dao;

import com.fdk.bean.ScheduleJob;
import com.fdk.bean.ScheduleJobExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScheduleJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job
     *
     * @mbggenerated Wed Nov 21 19:53:51 CST 2018
     */
    int countByExample(ScheduleJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job
     *
     * @mbggenerated Wed Nov 21 19:53:51 CST 2018
     */
    int deleteByExample(ScheduleJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job
     *
     * @mbggenerated Wed Nov 21 19:53:51 CST 2018
     */
    int deleteByPrimaryKey(Long jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job
     *
     * @mbggenerated Wed Nov 21 19:53:51 CST 2018
     */
    int insert(ScheduleJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job
     *
     * @mbggenerated Wed Nov 21 19:53:51 CST 2018
     */
    int insertSelective(ScheduleJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job
     *
     * @mbggenerated Wed Nov 21 19:53:51 CST 2018
     */
    List<ScheduleJob> selectByExample(ScheduleJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job
     *
     * @mbggenerated Wed Nov 21 19:53:51 CST 2018
     */
    ScheduleJob selectByPrimaryKey(Long jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job
     *
     * @mbggenerated Wed Nov 21 19:53:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") ScheduleJob record, @Param("example") ScheduleJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job
     *
     * @mbggenerated Wed Nov 21 19:53:51 CST 2018
     */
    int updateByExample(@Param("record") ScheduleJob record, @Param("example") ScheduleJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job
     *
     * @mbggenerated Wed Nov 21 19:53:51 CST 2018
     */
    int updateByPrimaryKeySelective(ScheduleJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job
     *
     * @mbggenerated Wed Nov 21 19:53:51 CST 2018
     */
    int updateByPrimaryKey(ScheduleJob record);
}