package com.fdk.dao;

import com.fdk.bean.SysMenu;
import com.fdk.bean.SysMenuExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SysMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Wed Nov 21 19:53:51 CST 2018
     */
    int countByExample(SysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Wed Nov 21 19:53:51 CST 2018
     */
    int deleteByExample(SysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Wed Nov 21 19:53:51 CST 2018
     */
    int deleteByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Wed Nov 21 19:53:51 CST 2018
     */
    int insert(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Wed Nov 21 19:53:51 CST 2018
     */
    int insertSelective(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Wed Nov 21 19:53:51 CST 2018
     */
    List<SysMenu> selectByExample(SysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Wed Nov 21 19:53:51 CST 2018
     */
    SysMenu selectByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Wed Nov 21 19:53:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysMenu record, @Param("example") SysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Wed Nov 21 19:53:51 CST 2018
     */
    int updateByExample(@Param("record") SysMenu record, @Param("example") SysMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Wed Nov 21 19:53:51 CST 2018
     */
    int updateByPrimaryKeySelective(SysMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbggenerated Wed Nov 21 19:53:51 CST 2018
     */
    int updateByPrimaryKey(SysMenu record);

    //树形结构 ,查找所有菜单
    List<SysMenu> findMenuNotButton();

    List<String> findPermsByUserId(long userid);

    List<Map<String,Object>> findParentMenuByUserId(long userId);

    //查询父目录下的子目录 @Param自动把数据封装成map格式
    List<Map<String,Object>> findMenuByUserId(@Param("userId") long userId,@Param("parentId") long parentId);



}